# Generated by Django 2.2.10 on 2020-06-16 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(default='Stop', max_length=255)),
                ('status', models.CharField(default='Active', max_length=255)),
            ],
            options={
                'db_table': 'Server',
            },
        ),
        migrations.CreateModel(
            name='ServerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ServerType',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('term_subscription', models.CharField(max_length=255)),
                ('service_type', models.CharField(default='Ipg', max_length=255)),
                ('subscription', models.CharField(max_length=255)),
                ('server_name_prefix', models.CharField(max_length=255)),
                ('package', models.CharField(max_length=255)),
                ('trunk_service_provider', models.CharField(max_length=255)),
                ('extra_call_record_package', models.CharField(max_length=255)),
                ('demo', models.CharField(max_length=255)),
                ('extra_duration_package', models.CharField(max_length=255)),
                ('state', models.CharField(default='Not Initialized ', max_length=255, null=True)),
            ],
            options={
                'db_table': 'subscription',
            },
        ),
        migrations.CreateModel(
            name='WebcmServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, null=True)),
                ('local_ip', models.CharField(max_length=255, null=True)),
                ('internal_ip', models.CharField(max_length=255, null=True)),
                ('server_name', models.CharField(max_length=255, null=True)),
                ('state', models.IntegerField(default=1, null=True)),
                ('fqdn', models.CharField(max_length=255, null=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.Server')),
            ],
            options={
                'db_table': 'WebcmServer',
            },
        ),
        migrations.AddField(
            model_name='server',
            name='server_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.ServerType'),
        ),
        migrations.AddField(
            model_name='server',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.Subscription'),
        ),
        migrations.CreateModel(
            name='IpgServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.CharField(max_length=255, null=True)),
                ('ram', models.CharField(max_length=255, null=True)),
                ('disc', models.CharField(max_length=255, null=True)),
                ('widea_address', models.CharField(max_length=255, null=True)),
                ('local_ip', models.CharField(max_length=255, null=True)),
                ('internal_ip', models.CharField(max_length=255, null=True)),
                ('external_ip', models.CharField(max_length=255, null=True)),
                ('server_name', models.CharField(max_length=255, null=True)),
                ('state', models.IntegerField(default=1, null=True)),
                ('fqdn', models.CharField(max_length=255, null=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.Server')),
            ],
            options={
                'db_table': 'IpgServer',
            },
        ),
    ]
