# Generated by Django 2.2.10 on 2020-07-02 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='idstr',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
