# Generated by Django 2.2.10 on 2020-07-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_server_idstr'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='exp20_dss_module_ip1141',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='subscription',
            name='exp40_dss_module_ip136_ip138',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='subscription',
            name='ip1111_poe_no_adapter',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='subscription',
            name='ip1131_poe_gigabit_no_adapter',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='subscription',
            name='ip1141_ip131_ip132_adapter',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='subscription',
            name='ip1141_poe_no_adapter',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='subscription',
            name='ip1181_ip136_ip138_adapter',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='subscription',
            name='ip1211_ip1211p_ip1111_ip1131_adapter',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='subscription',
            name='ip1211_poe_no_adapter',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='subscription',
            name='ip1211_w_adapter',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='subscription',
            name='ip131_poe_no_adapter',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='subscription',
            name='ip132_gigabit_no_adapter',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='subscription',
            name='ip136_poe_no_adapter',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='subscription',
            name='ip138_poe_no_adapter',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='subscription',
            name='karel_mobile',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='subscription',
            name='vp128',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='subscription',
            name='yt510',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='subscription',
            name='yt520',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='subscription',
            name='yt530',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
